name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    # Add PostgreSQL service
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: laravel_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # Setup PHP (use a specific version that matches your requirements)
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo_pgsql
        
    # Checkout code
    - uses: actions/checkout@v4
    
    # Copy .env file
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    # Install dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    # Generate app key
    - name: Generate key
      run: php artisan key:generate
      
    # Set directory permissions
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    # Configure database in env
    - name: Configure Database
      run: |
        echo "DB_CONNECTION=pgsql" >> .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_DATABASE=laravel_test" >> .env
        echo "DB_USERNAME=postgres" >> .env
        echo "DB_PASSWORD=postgres" >> .env
        echo "SALT=ci-testing-salt" >> .env
      
    # Run migrations
    - name: Run migrations
      run: php artisan migrate --force
      
    # Create roles and permissions
    - name: Setup roles and permissions
      run: |
        php artisan roles:create
        php artisan permissions:create
      
    # Run tests
    - name: Execute tests
      run: php artisan test
      
    # Generate API docs
    - name: Generate API documentation
      run: php artisan l5-swagger:generate